language: node_js
node_js:
  - 6
cache:
  directories:
    - ~/.npm
    - node_modules
    - "$HOME/google-cloud-sdk/"
env:
  - PATH=$PATH:${HOME}/google-cloud-sdk/bin CLOUDSDK_CORE_DISABLE_PROMPTS=1
before_install:
  - gcloud version || true
  - if [ ! -d "$HOME/google-cloud-sdk/bin" ]; then rm -rf $HOME/google-cloud-sdk; export CLOUDSDK_CORE_DISABLE_PROMPTS=1; curl https://sdk.cloud.google.com | bash; fi
  # Add gcloud to $PATH
  - source /home/travis/google-cloud-sdk/path.bash.inc
  - openssl aes-256-cbc -K $encrypted_b846672fbe33_key -iv $encrypted_b846672fbe33_iv -in credentials.tar.gz.enc -out credentials.tar.gz -d
  - tar -xzf credentials.tar.gz
  - gcloud auth activate-service-account --key-file service-account.json
install:
  - yarn
  - npm run webpack

jobs:
  include:
    - stage: E2E bundle.web.js Tests
      script:
        - $(npm bin)/cypress run
