sudo: true
language: node_js
node_js:
  - 6
cache:
  directories:
    - ~/.npm
    - node_modules
    - "$HOME/google-cloud-sdk/"
env:
  - CLOUDSDK_CORE_DISABLE_PROMPTS=1
before_install:
  - if [ ! -d "$HOME/google-cloud-sdk" ]; then
      export CLOUD_SDK_REPO="cloud-sdk-$(lsb_release -c -s)";
      echo "deb http://packages.cloud.google.com/apt $CLOUD_SDK_REPO main" | sudo tee -a /etc/apt/sources.list.d/google-cloud-sdk.list;
      curl https://packages.cloud.google.com/apt/doc/apt-key.gpg | sudo apt-key add - ;
      sudo apt-get update && sudo apt-get install google-cloud-sdk;
    fi
  # Add gcloud to $PATH #
  # - source /home/travis/google-cloud-sdk/path.bash.inc
  - openssl aes-256-cbc -K $encrypted_b846672fbe33_key -iv $encrypted_b846672fbe33_iv -in credentials.tar.gz.enc -out credentials.tar.gz -d
  - tar -xzf credentials.tar.gz
  # - gcloud auth activate-service-account --key-file service-account.json
install:
  - yarn
  # - npm run webpack

script:
  - $(npm bin)/cypress run
